baseURL = "https://rebooos.github.io"
languageCode = "en-us"
title = "Morozov D"
copyright = "Copyright Â© 2021, Morozov Dmitrii and the Hugo Authors; all rights reserved."
theme = "npq-hugo"
pygmentsUseClasses=true

[params]
  author = "Dmitrii"
  description = "Developer"
  keywords = "My personal page"
  useAvatar = true
  microBlogSection = "posts"
  displayMicroBlog = false
  displayRecent = true
  displayHomeContent = false
  recentMax = 4
  mail = "dvmorozov74@gmail.com"

[menu]
  [[menu.main]]
    name = "CV"
    pre = "<i class=\"fas fa-home fa-sm\"></i>"
    url = "/default"
    weight = -9
  [[menu.main]]
    name = "It's me"
    pre = "<i class=\"fab fa-github fa-ms\"></i>"
    url = "/hobby"
    weight = -6
  [[menu.main]]
    name = "github"
    pre = "<i class=\"fab fa-github fa-ms\"></i>"
    url = "https://github.com/rebooos"
    weight = -6 
  [[menu.main]]
    name = "contact"
    pre = "<i class=\"far fa-envelope\"></i>"
    url = "/contact"
    weight = -1 
